kind: PersistentVolume
apiVersion: v1
metadata:
  name: kube-registry-pv
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-a4f49e0b
    fsType: ext4
