#!/bin/sh
set -e

if [ `whoami` != "root" ]; then
    echo "This script must be run as root"
    exit 1
fi

cd $(dirname "$0")

for file in /home/*/.*history /root/.*history; do
    if [ -h "$file" ] && [ "$(readlink "$file")" = "/dev/null" ]; then
        rm -f "$file"
    fi
done

cat > ~fusion/.ssh/userkey.pub
cat fusiondev.pub ~fusion/.ssh/userkey.pub > ~fusion/.ssh/authorized_keys
cat fusiondev.pub ~fusion/.ssh/userkey.pub > ~ubuntu/.ssh/authorized_keys
chown -R fusion:fusion ~fusion/.ssh

cp post-deploy ~fusion
