#!/bin/sh
set -e

if [ "$VERSION" = "" ]; then
    echo "A VERSION must be passed"
    exit 1
fi

if [ "$DIR" = "" ]; then
    echo "A DIR must be passed"
    exit 1
fi

# RSI: verify VERSION is the latest version

if [ ! -e ~/deploy/"$DIR" ]; then
    echo "Deploy $DIR does not exist in ~/deploy"
    exit 1
fi

# NB: this is atomic
ln -nsf ~/deploy/"$DIR" ~/deploy/current_new
mv -T ~/deploy/current_new ~/deploy/current
