apiVersion: v1
kind: Service
metadata:
  name: hzc-ssh
  labels:
    app: hzc-ssh
spec:
  type: LoadBalancer
  selector:
    app: hzc-ssh
  ports:
  - port: 22
    targetPort: 2222
    name: ssh
    protocol: TCP
