apiVersion: v1
kind: Service
metadata:
  name: hzc-http
  labels:
    app: hzc-http
spec:
  type: LoadBalancer
  selector:
    app: hzc-http
  ports:
  - port: 80
    targetPort: 8080
    name: http
    protocol: TCP
  - port: 443
    targetPort: 4433
    name: https
    protocol: TCP
