apiVersion: v1
kind: Service
metadata:
  name: hzc-varnish
  labels:
    app: hzc-varnish
spec:
  type: NodePort
  selector:
    app: hzc-varnish
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32222
    name: http
    protocol: TCP
