#!/bin/bash
set -eu
set -o pipefail

running=`mktemp -d`
trap "rm -rf $running" EXIT

for target in "$@"; do
    echo "Building and pushing $target"
    pushd "$target" >/dev/null
    tname=`basename "$target"`

    {
        set -eux
        set -o pipefail

        echo "${target%/}" > "$running/$tname"

        if [[ -f prepare ]]; then
            ./prepare
        fi
        image_id=`docker build . | tee build.log | tail -1 | awk '{print $3}'`
        gcr_image_id="us.gcr.io/horizon-cloud-1239/$tname:$image_id"
        docker tag -f "$image_id" "$gcr_image_id"
        gcloud docker push "$gcr_image_id"
        echo "$gcr_image_id" > "gcr_image_id"

        rm "$running/$tname"
    } &> deploy.log &

    popd >/dev/null
done

wait

shopt -s nullglob
exit_code=0
for remaining in $running/*; do
    exit_code=1
    echo "Failed to build or push `basename $remaining`:"
    cat `cat $remaining`/deploy.log
    echo
done

exit $exit_code
