#!/bin/bash
set -eu
set -o pipefail

for target in "$@"; do
    basename=`basename "$target"`
    name=${basename%%.*}
    current=`kubectl get rc | grep "^$name--" | cut -d ' ' -f 1`
    if [[ -z "$current" ]]; then
        echo "No replication controller found for $target, exiting."
        exit 1
    fi
    current1=`echo "$current" | head -1`
    if [[ "$current" != "$current1" ]]; then
        echo "Multiple replication controllers found for $target, exiting:"
        echo "$current"
        exit 1
    fi

    if [[ "${target:0:1}" == "/" ]]; then
        exec_target="$target"
    else
        exec_target="./$target"
    fi

    template_expansion=`$exec_target`
    template_name=`echo "$template_expansion" \
      | grep -F "name: $name--" \
      | sed -e 's/.*: //'`
    if [[ "$template_name" == "$current" ]]; then
        echo "Replication controller $current is already up to date."
        exit 0
    fi

    echo "Updating $current to $template_name..."
    $exec_target | kubectl rolling-update "$current1" -f -
done
