apiVersion: v1
kind: Service
metadata:
  name: rethinkdb-sys
spec:
  type: ClusterIP
  clusterIP: "None" # Headless service
  selector:
    app: rethinkdb-sys
  ports:
  - port: 28015
    targetPort: 28015
    name: driver
    protocol: TCP
  - port: 8080
    targetPort: 8080
    name: webui
    protocol: TCP
