package hzhttp

import "net/http"

// Most of the guts are in responsewriter_generated.go, generated by:
//go:generate go run mkresponsewriter/main.go -o responsewriter_generated.go

type responseWriterState struct {
	Status   int
	Transfer transferStats
}

type responseWriterType struct {
	Hijacker      bool
	Flusher       bool
	CloseNotifier bool
}

func wrapResponseWriter(w http.ResponseWriter, rws *responseWriterState) http.ResponseWriter {
	_, isHijacker := w.(http.Hijacker)
	_, isFlusher := w.(http.Flusher)
	_, isCloseNotifier := w.(http.CloseNotifier)
	typ := responseWriterType{
		Hijacker:      isHijacker,
		Flusher:       isFlusher,
		CloseNotifier: isCloseNotifier,
	}
	return responseWriterConstructors[typ](w, rws)
}
