#!/bin/bash
set -e
set -x

mkdir deploy
mkdir deploy/empty-site
echo "<html><body>Nothing has been deployed here yet!</body></html>" \
    > deploy/empty-site/index.html
ln -s empty-site deploy/current

mkdir fusion
tar -xz -C fusion -f fusion-tarball.tar.gz
rm fusion-tarball.tar.gz

pushd fusion/client
npm install --no-progress || npm install --no-progress
node build.js
popd

pushd fusion/server
npm install --no-progress || npm install --no-progress
popd
