#!/bin/bash
set -e
set -x

cd $(dirname $0)

if [[ $RUNSETUP != "YES" ]]; then
    echo "Do not run this except during AMI creation!"
    echo "Set the environment variable RUNSETUP to YES to skip this check."
    exit 1
fi

if [[ $(whoami) != "root" ]]; then
    echo "This script must be run as root"
    exit 1
fi

. /etc/lsb-release

# Add RethinkDB repository
echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" \
    > /etc/apt/sources.list.d/rethinkdb.list
curl -s https://download.rethinkdb.com/apt/pubkey.gpg | apt-key add -

# Update package lists and install stuff
apt-get update
apt-get dist-upgrade -y
apt-get install -y \
    build-essential \
    nginx \
    rethinkdb \
    runit

# Install node/npm using their binaries (ubuntu's are very old)
curl -O https://nodejs.org/dist/v4.2.6/node-v4.2.6-linux-x64.tar.xz
echo "919498f2eb855ef0468b428b97d9d3f604d0f83417502d65b98c136786eb94d5 *node-v4.2.6-linux-x64.tar.xz" \
    | sha256sum -c -
tar -xJf node-v4.2.6-linux-x64.tar.xz
rm node-v4.2.6-linux-x64.tar.xz
pushd node-v4.2.6-linux-x64
rsync -a bin include lib share /usr/local/
popd
rm -rf node-v4.2.6-linux-x64

# Setup the fusion user
useradd -m fusion
mv fusion-tarball.tar.gz ~fusion/fusion-tarball.tar.gz
chown fusion:fusion ~fusion/fusion-tarball.tar.gz
su - fusion -c /bin/bash < setup-fusionuser

# Move daemon config files into place
mv fusion-server-service /etc/service/fusion-server
mv rethinkdb-default.conf /etc/rethinkdb/instances.d/default.conf
rm /etc/nginx/sites-enabled/*
mv nginx-fusion.conf /etc/nginx/sites-enabled/fusion.conf

# wait for runsv to be started for all services
for service in /etc/service/*; do
    while [[ ! -e $service/supervise ]]; do
        sleep 1
    done
done

################################################################################
# Clean up files containing state before packaging the AMI

cd /
rm -rf $(dirname $0)

# stop services
/etc/init.d/rethinkdb stop
/etc/init.d/nginx stop
sv stop /etc/service/*
sv stop /etc/service/*/log

# remove logs, keys and user data
rm -f /etc/service/*/log/*.s
rm -f /etc/service/*/log/current
rm -f /var/log/nginx/*
rm -rf /var/lib/rethinkdb/default/data

for delete in \
    /etc/ssh/*_key \
    /etc/ssh/*_key.pub \
    /home/*/.*history \
    /root/.*history; do

    if [ -e "$delete" ]; then
        shred -u "$delete"
    fi
done

echo "Ready for shutdown and AMI creation"
