#!/bin/bash
set -eu

# Disabling cgo avoids linking to libc for DNS resolution support, and thus makes
# a truly static binary.

CGO_ENABLED=0 go build -o hzc-ssh \
    github.com/rethinkdb/horizon-cloud/cmd/hzc-ssh
